setwd("/Users/timothybarraclough/Documents/teaching/CMEE.2015/bacteria.multispecies")
library(deSolve)
##load in functions
source("functions.R")
##load in the model code
source("main.v4.R")

##Times for each simulation run
times<-seq(0,500,0.5)  

##0) Number of species and substrates
kNumSpec<-4			     		
kNumSubst<-5

##1) substrate concentrations in the inflow, initial concentrations and their dilution rate
kInflowConc<-rep(0,kNumSubst)
kInflowConc[1]<-3
conc.subst <- kInflowConc
kSubstDilutionRate<-0.01

##2) species at start and their dilution rate
density.spec<-rep(0.1,kNumSpec)
#density.spec[2]<-0
kSpecDilutionRate<-kSubstDilutionRate

##3) assign the pathway
pathway <-array(FALSE,dim=c(kNumSubst,kNumSubst,kNumSpec))
pathway[1,2,]<-TRUE
pathway[2,3:4,]<-TRUE
pathway[3,5,]<-TRUE
pathway[4,5,]<-TRUE

kNumReac<-sum(pathway[,,1])
##set to false if any species are missing
if (min(density.spec)==0) {pathway[,, density.spec ==0]<-FALSE}
whole.pathway<-apply(pathway,c(1,2),any)

##4) Evolve or not? If so, assign positive mutation rate
 evolve<-TRUE
  kMutRate<-array(data = 0.0, dim = c(kNumSubst,kNumSubst,kNumSpec))
  if (evolve) kMutRate[pathway]<-0.05
  ##assign cost of generalism: 1 = linear trade-off; >1 = generalists penalized
  cost.generalism<-1.0


##CODE TO RUN SIMULATION STARTS HERE
ptm <- proc.time()

##The metabolic traits:

##need same value for diverging reactions##

##5) number of ATP molecules generated by each reaction i->j in species k                               	
  kAtpPerReaction <-array(data = 0, dim=c(kNumSubst,kNumSubst,kNumSpec))
  ##assumes constant for each reaction irrespective of species
  kAtpPerReaction[pathway]<-1
	
##6) Michaelis constant for the enzyme that catalyses reaction i->j in species k  
  kMichaelis <-array(data =1, dim = c(kNumSubst,kNumSubst,kNumSpec))

##7) kCat[i,j,k] = turnover number for the enzyme that catalyses reaction i->j in species k 
  kCat <-array(data =0.2, dim = c(kNumSubst,kNumSubst,kNumSpec))

##8) Allocate enzymes => 1 species metabolising each resource, with equal allocation to each if a fork
	##where pathways split, do EVEN amounts go each way or RANDOM partition, in specialist case
	metabolic <-array(data = 0, dim=c(kNumSubst,kNumSubst,kNumSpec))	
	##species 1 converts substrate 1 to 2
	metabolic[1,2,1]<-1
	##species 2 converts substrate 2 to 3 and 4.
	metabolic[2,3:4,2]<-c(0.7,0.3)
	##species 3 converts substrate 3 to 5
	metabolic[3,5,3]<-1
	##species 4 converts substrate 3 to 5
	metabolic[4,5,4]<-1

	
##run the code and store in results	
results<-main()

##pull out S, N and E from final results line
S<-results$sol[length(times),-1][1:kNumSubst]
N<-results$sol[length(times),-1][(1+ kNumSubst):(kNumSubst+kNumSpec)]
E<-results$sol[length(times),-1][(kNumSubst+kNumSpec+1):(kNumSubst+kNumSpec +sum(pathway))]


(proc.time() - ptm)[3]


##make the plots to show the results	
source("plots.eco.R")
main.plot(results$sol)

